In [64]:
import numpy as np 
import numpy as np
from scipy.sparse import csr_matrix
import pandas as pd

In [23]:
data_set = np.load('user_movie_rating.npy')

In [65]:
df = pd.DataFrame(data_set)

In [71]:
df.rename(columns=  {0:'user_id',1:'movie_id',2:'rating'},inplace = True)

In [26]:
df_p

array([[     1,     30,      3],
       [     1,    157,      3],
       [     1,    173,      4],
       ...,
       [103703,  17622,      2],
       [103703,  17627,      4],
       [103703,  17764,      4]], dtype=int64)

In [7]:
test_array = np.random.randint(0,2,size = [10,5])

In [27]:
tmp = test_array

In [16]:
perm = np.arange(10)

In [49]:
np.random.shuffle(perm)

In [50]:
perm

array([9, 4, 2, 6, 8, 1, 0, 5, 3, 7])

In [51]:
permuted_tmp = tmp[perm]

In [52]:
permuted_tmp

array([[0, 1, 0, 1, 1],
       [1, 0, 1, 1, 1],
       [1, 0, 0, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 1, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 0, 0, 0],
       [1, 1, 0, 1, 1]])

In [53]:
np.argmax(permuted_tmp,axis = 0)

array([1, 0, 1, 0, 0], dtype=int64)