In [1]:
import numpy as np

In [2]:
t1 = np.array([1,2,0,2,5,0,0,6,0,1,0])

In [5]:
t1.astype('bool').astype(int)

array([1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0])

In [2]:
matrix = np.random.randint(0,5,[5,7])

In [324]:
np.dot(matrix[:,4],plane)

-4

In [320]:
plane = np.random.randint(-1,2,5)
np.dot(plane.T,matrix)

array([-5, -4, -5,  0, -4, -6, -4])

In [313]:
np.dot([1,2,-1,2],[0,1,0,1])

4

array([15,  8,  9, 17, 20,  0,  8])

In [251]:
import numpy as np

def random_projection_hash(input_vector, projection_matrix, threshold):
    hashed_value = np.dot(input_vector, projection_matrix)
    hash_code = int(hashed_value >= threshold)
    return hash_code

# Example usage:
dimension = 10  # Dimensionality of the input vector
threshold = 0.5  # Adjust the threshold as needed

# Generate a random projection matrix with integer values between 0 and 1
projection_matrix = np.random.randint(-1,1,dimension)

# Generate a random input vector of integers between 0 and 5 for demonstration purposes
input_vector = np.random.randint(6, size=dimension)

# Hash the input vector using random projection into two buckets
hash_code = random_projection_hash(input_vector, projection_matrix, threshold)

print("Input Vector:", input_vector)
print("Hash Code:", hash_code)

Input Vector: [0 2 2 0 5 2 2 2 5 5]
Hash Code: 0
